<?php
namespace ccxt;
include_once (__DIR__.'/../../ccxt.php');
// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -----------------------------------------------------------------------------

error_reporting(E_ALL | E_STRICT);
date_default_timezone_set('UTC');

use ccxt\Precise;
use React\Async;
use React\Promise;


// AUTO-TRANSPILE //
function example() {
    return Async\async(function () {
        $allin = new \ccxt\pro\allin(array(
            'apiKey' => 'MG9pDxDRRRJZkuFDAVK6RZyiexsXKN',
            'secret' => 'jN2j4gnUPyaOD3wVDoOZpyq5s8ymCgYN4khCwp2aEnsOf4W1na',
            'options' => array(
                'defaultType' => 'spot',
            ),
        ));
        $allin->set_sandbox_mode(true);
        $symbol = 'BTC/USDT';
        while (true) {
            $orders = Async\await($allin->watch_orders($symbol));
            var_dump('orders: ', $orders);
        }
    }) ();
}


Async\await(example());
