// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class allin : Exchange
{
    public allin (object args = null): base(args) {}

    public async Task<object> publicGetOpenV1TickersMarket (object parameters = null)
    {
        return await this.callAsync ("publicGetOpenV1TickersMarket",parameters);
    }

    public async Task<object> publicGetOpenV1DepthMarket (object parameters = null)
    {
        return await this.callAsync ("publicGetOpenV1DepthMarket",parameters);
    }

    public async Task<object> publicGetOpenV1TradeMarket (object parameters = null)
    {
        return await this.callAsync ("publicGetOpenV1TradeMarket",parameters);
    }

    public async Task<object> publicGetOpenV1KlineMarket (object parameters = null)
    {
        return await this.callAsync ("publicGetOpenV1KlineMarket",parameters);
    }

    public async Task<object> privateGetOpenV1TickersExchangeInfo (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1TickersExchangeInfo",parameters);
    }

    public async Task<object> privateGetOpenV1Tickers (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1Tickers",parameters);
    }

    public async Task<object> privateGetOpenV1Balance (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1Balance",parameters);
    }

    public async Task<object> privateGetOpenV1Timestamp (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1Timestamp",parameters);
    }

    public async Task<object> privateGetOpenV1Kline (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1Kline",parameters);
    }

    public async Task<object> privateGetOpenV1Depth (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1Depth",parameters);
    }

    public async Task<object> privateGetOpenV1TickersTrade (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1TickersTrade",parameters);
    }

    public async Task<object> privateGetOpenV1OrdersLast (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1OrdersLast",parameters);
    }

    public async Task<object> privateGetOpenV1Orders (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1Orders",parameters);
    }

    public async Task<object> privateGetOpenV1OrdersDetail (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1OrdersDetail",parameters);
    }

    public async Task<object> privateGetOpenV1OrdersDetailmore (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1OrdersDetailmore",parameters);
    }

    public async Task<object> privateGetOpenV1OrdersFeeRate (object parameters = null)
    {
        return await this.callAsync ("privateGetOpenV1OrdersFeeRate",parameters);
    }

    public async Task<object> privatePostOpenV1OrdersPlace (object parameters = null)
    {
        return await this.callAsync ("privatePostOpenV1OrdersPlace",parameters);
    }

    public async Task<object> privatePostOpenV1OrdersCancel (object parameters = null)
    {
        return await this.callAsync ("privatePostOpenV1OrdersCancel",parameters);
    }

    public async Task<object> privatePostOpenV1OrdersBatcancel (object parameters = null)
    {
        return await this.callAsync ("privatePostOpenV1OrdersBatcancel",parameters);
    }

}